version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
      day: "friday"
    rebase-strategy: "disabled"
    open-pull-requests-limit: 20

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "friday"
    rebase-strategy: "disabled"
    open-pull-requests-limit: 20
