version: '3'
services:
  full-teaching-mysql:
    container_name: full-teaching-mysql-${tjobname}
    image: mysql:5.7.21
    init: true
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=full_teaching
      - MYSQL_USER=ft-root
      - MYSQL_PASSWORD=pass
    networks:
      - jenkins_network
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  full-teaching-openvidu-server-kms:
    container_name: full-teaching-${tjobname}-openvidu-server-kms
    image: ${OpenViduImage}
    init: true
    expose:
      - 8443
    environment:
      - KMS_STUN_IP=stun.l.google.com
      - KMS_STUN_PORT=19302
      - openvidu.secret=MY_SECRET
      - openvidu.publicurl=https://full-teaching-${tjobname}-openvidu-server-kms:8443
    networks:
      - jenkins_network
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  full-teaching:
    container_name: full-teaching-${tjobname}
    image: codeurjc/full-teaching:demo
    init: true
    depends_on:
      - full-teaching-mysql
      - full-teaching-openvidu-server-kms
    expose:
      - 5000
    environment:
      - WAIT_HOSTS=full-teaching-mysql-${tjobname}:3306
      - WAIT_HOSTS_TIMEOUT=120
      - MYSQL_PORT_3306_TCP_ADDR=full-teaching-mysql-${tjobname}
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_ENV_MYSQL_DATABASE=full_teaching
      - MYSQL_ENV_MYSQL_USER=ft-root
      - MYSQL_ENV_MYSQL_PASSWORD=pass
      - server.port=5000
      - openvidu.url=https://full-teaching-${tjobname}-openvidu-server-kms:8443
      - openvidu.secret=MY_SECRET
    networks:
      - jenkins_network
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  jenkins_network:
    external: true