sonar.organization=giis
sonar.projectKey=my:retorch-st-fullteaching
sonar.projectName=retorch-st-fullteaching

sonar.sources=sut/src/main/java
sonar.tests=sut/src/test/java
sonar.java.binaries=sut/target/classes
sonar.java.test.binaries=sut/target/test-classes

sonar.coverage.jacoco.xmlReportPaths=sut/target/site/jacoco/jacoco.xml

sonar.sourceEncoding=UTF-8
# Exclude pre-built Angular bundles checked into the repo
sonar.exclusions=sut/src/main/resources/static/**