name: build
on:
  push:
#    branches-ignore:
#      - 'dependabot/**' #avoid duplicates: only run the PR, not the commit
#      - 'gh-pages' #github pages do not trigger all tests
#    tags-ignore:
#      - 'v*' #avoid rerun existing commit on release
#  pull_request:
#    branches:
#      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    #if: ${{ false }}  # disable for now
    permissions:
      statuses: write
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: pass
          MYSQL_DATABASE: full_teaching
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v6
      - name: Select Java Version
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Init jenkins commit status (optional)
        run: |
          curl -L -X POST  https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             -d "{\"state\":\"pending\", \"context\":\"Jenkins CI\"}"

      - name: Compile and test SUT, generate JaCoCo coverage report
        run: mvn verify -B --no-transfer-progress
        working-directory: sut

      - name: Save JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: sut/target/site/jacoco/
          retention-days: 7

      - name: Build E2E test suite
        run: mvn test-compile -U --no-transfer-progress

      - name: SonarCloud analysis
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
